### ISSUE TITLE
Rust implementation?

### ISSUE THREAD

**Issue by SilentCicero** [ethereum-optimism/asterisc#1]
Any plans for a Rust implementation for the proving architecture?

**Comment by protolambda** [comment]
Not currently. And for now I'm prioritizing work on https://github.com/ethereum-optimism/cannon/ but do plan to continue development on Asterisc to match the same ABI and CLI interface. Maybe other implementations in Rust can do the same, by all following the ABI specs in https://github.com/ethereum-optimism/optimism/blob/develop/specs/fault-proof.md
