### ISSUE TITLE
Asterisc Task Tracker

### ISSUE THREAD

**Issue by pcw109550** [ethereum-optimism/asterisc#18]
This issue gives an overview to taking Asterisc to the current Cannon's level. Expected to be a superset of proto's TODOs: https://github.com/ethereum-optimism/asterisc/issues/7.

Cannon-compatible CLI commands
- https://github.com/ethereum-optimism/asterisc/pull/8
- https://github.com/ethereum-optimism/asterisc/pull/15
- https://github.com/ethereum-optimism/asterisc/pull/56

Contracts integration
- https://github.com/ethereum-optimism/asterisc/pull/9
- https://github.com/ethereum-optimism/asterisc/pull/10
- https://github.com/ethereum-optimism/asterisc/pull/11
- https://github.com/ethereum-optimism/asterisc/pull/13
- https://github.com/ethereum-optimism/asterisc/pull/17
- https://github.com/ethereum-optimism/asterisc/pull/19
- https://github.com/ethereum-optimism/asterisc/pull/20
- https://github.com/ethereum-optimism/asterisc/pull/26
- https://github.com/ethereum-optimism/asterisc/pull/30

VM Fixes
- https://github.com/ethereum-optimism/asterisc/pull/32
- https://github.com/ethereum-optimism/asterisc/pull/33
- https://github.com/ethereum-optimism/asterisc/pull/52
- https://github.com/ethereum-optimism/asterisc/pull/54
- Check `op-program` complied using `go 1.22` can be run at asterisc. Cannon failed with error `cannot open standard fds`: https://github.com/ethereum-optimism/asterisc/pull/84

Add more tests
- https://github.com/ethereum-optimism/asterisc/pull/22
- https://github.com/ethereum-optimism/asterisc/pull/21
- https://github.com/ethereum-optimism/asterisc/pull/23
- https://github.com/ethereum-optimism/asterisc/pull/31
- https://github.com/ethereum-optimism/asterisc/pull/34
- https://github.com/ethereum-optimism/asterisc/pull/29
- https://github.com/ethereum-optimism/asterisc/pull/42
- https://github.com/ethereum-optimism/asterisc/pull/55

CI
- https://github.com/ethereum-optimism/asterisc/pull/28
- https://github.com/ethereum-optimism/asterisc/pull/27
- https://github.com/ethereum-optimism/asterisc/pull/40
- https://github.com/ethereum-optimism/asterisc/pull/39
- https://github.com/ethereum-optimism/asterisc/pull/47
- https://github.com/ethereum-optimism/asterisc/pull/53
- https://github.com/ethereum-optimism/asterisc/pull/51

Test `op-program` using asterisc
- https://github.com/ethereum-optimism/asterisc/pull/16
- More op-program tests with prod chain data: Sampling 8% blocks of op-mainnet.

Deployment
- https://github.com/ethereum-optimism/asterisc/pull/26
- https://github.com/ethereum-optimism/asterisc/pull/67
- https://github.com/ethereum-optimism/asterisc/pull/70
- https://github.com/ethereum-optimism/asterisc/pull/72

Misc
- https://github.com/ethereum-optimism/asterisc/pull/25
- https://github.com/ethereum-optimism/asterisc/pull/43
- https://github.com/ethereum-optimism/asterisc/pull/49
- https://github.com/ethereum-optimism/asterisc/pull/61

**Comment by mininny** [comment]
Closing as all tasks are complete.
