### ISSUE TITLE
[Bug] The binary doesn't compile

### ISSUE THREAD

**Issue by borispovod** [ethereum-optimism/asterisc#3]
Hello,

First off, thank you for this fantastic project.

When I attempt to compile, I encounter the following error:

```
main.go:9:2: no required module provides package github.com/protolambda/asterisc/rvgo/oracle; to add it:
        go get github.com/protolambda/asterisc/rvgo/oracle
```

However, this isn't the only issue. It appears that after some code refactoring, `main.go` might not have been updated accordingly.

 I've managed to make some modifications to `main.go` to get it running with the new logic (looked at tests). Still, I believe it requires further refinement. I'm not currently in a position to submit a PR, but I hope to do so in the near future.

**Comment by protolambda** [comment]
Thanks for opening the issue. This project is still in an experimentation phase, tests run but the CLI entrypoint may be broken. I'll revisit this the next time I work on the CLI part of asterisc

**Comment by pcw109550** [comment]
Now you may able to compile. Multiple CI step checks this.
