### ISSUE TITLE
Excessive memory usage serialising state snapshots

### ISSUE THREAD

**Issue by ajsutton** [ethereum-optimism/asterisc#77]
When a client program uses a large amount of memory (~3GiB in my test case), serialising the state snapshot to JSON uses an excessive amount of system memory.  For a 3GiB state serialising the state consumed 64Gb of system memory and was killed by the OOM killer.

In cannon the memory pages are [compressed before serialising to JSON](https://github.com/ethereum-optimism/optimism/blob/4584c9764a2599d15d65be5230973e2a8c8d7b2e/cannon/mipsevm/memory/page.go#L25-L37) however that's a pretty rubbish solution and is probably insufficient given asterisc is 64bit so the client memory usage can be very high.

The ideal solution would be a state snapshot format that can be streamed rather than needing to serialise it as bytes in memory first before writing out.

**Comment by mininny** [comment]
@ajsutton Do you think this could be closed since we changed the JSON Serialization to binary serialization here https://github.com/ethereum-optimism/asterisc/pull/82? We probably would need to validate the performance improvement, though.

**Comment by mininny** [comment]
Closing as it's complete as of above comment
